### ISSUE TITLE
How to use Tachyon's '.cf' class?

### ISSUE THREAD

**Issue by sladiri** [jamesmcallister/styled-components-tachyons#15]
Hi, how do you use this so that `.cf`, `.cf:after` etc. get applied?
https://github.com/tachyons-css/tachyons/blob/fd38efabc264542b1bc31f727e942736ea57ecd0/src/_clears.css#L11-L14
```
const H1 = styled.h1`${tachyons}`;
<H1 cf>Test</H1>
// only .cf is applied
```

I am also confused why here `hover_orange` works, but `shadow_hover` does not, how should I use `shadow_hover`?:
`<H1 hover_orange shadow_hover>Test</H1>`
https://github.com/tachyons-css/tachyons/blob/580f953d18307f72619812516abf95c799fb0c65/src/_hovers.css#L127-L149

**Comment by jamesmcallister** [comment]
Have a look in the `bundle.js` file in your `node_modules/styled-components-tachyons` and do a search for the classes you want to use. 

`cf:after` needs to be used as `cf_after`
`shadow_hover` needs to be used as `shadow_hover__after`

I took me awhile to think about, but looking through the `bundle.js` file it jumped out at me.

**Comment by sladiri** [comment]
Thank you, I will try it out. I thought that they might not be supported yet.

**Comment by jamesmcallister** [comment]
If you get stuck, have a look at this file. [These are blacklisted](https://github.com/jamesmcallister/tachyons-js/blob/master/generate.js#L7-L22)
