### ISSUE TITLE
Question about tachyons vs sc

### ISSUE THREAD

**Issue by dan-weaver** [jamesmcallister/styled-components-tachyons#8]
I really like tachyons and am very interested in styled-components.  I noticed @mxstbr 's comment and thought this might be a good place to ask this question since it involves both libraries / philosophies!

I'm still trying to understand styled-components, so this may be misguided, but don't these two philosophies sort of contradict each other?  I was under the impression that styled-components sort of protected components from ad-hoc styling whereas tachyons really promotes it through it's utility style classes.  What advantage is left after implementing tachyons in styled-components?  Not that either paradigm is necessarily better, but they seem to be at odds.

EDIT: being more specific, styled-components is about "removing the mapping of styles / classes to components".  Wouldn't implementing tachyons in sc be adding that mapping right back?

Thanks!

**Comment by jamesmcallister** [comment]
It was more to do with keeping css functional, as Tachyons is. 

To be honest I'm not sure its a good idea... but it was at the time and a few others seem to like the idea. 

Have a play and see how it works for you.

**Comment by Morganjackson** [comment]
I love it!

@dan-weaver Have you seen this [discussion](https://github.com/styled-components/styled-components/issues/494#issuecomment-297863420)? I found some great examples in there.

**Comment by dan-weaver** [comment]
@Morganjackson thanks for pointing that out. hadn't seen it.  Some interesting debate in there indeed.
