### ISSUE TITLE
Handling css variables from tachyons

### ISSUE THREAD

**Issue by dan-weaver** [jamesmcallister/styled-components-tachyons#9]
As mentioned here, https://github.com/jongold/tachyons-js/issues/2, I don't see any clear way of handling the replacement of css variables.  Not sure if this functionality should be in tachyons-js or this library though.  Any ideas?

**Comment by jamesmcallister** [comment]
This would think this would be down to styled-components. [Have a read here](https://github.com/styled-components/styled-components/issues/108)

**Comment by YoungElPaso** [comment]
From reading that thread I dunno if the plan is to replace the variables, looks like the general idea is to just use em or replace them with JS, which doesn't really scale in this case (using predefined tachyons vars). 

[tachyons](https://github.com/jongold/tachyons-js) recommends just importing the css variables (see near the top of the Readme).  That'll just append them all into a :root pseudo selector and the browser will handle the variables (or not depending on support).

That's a work-around that works for me for now.

**Comment by dan-weaver** [comment]
@YoungElPaso yeah that's what I'm doing.. I feel like there should be some kind of extension point somewhere in one of these libraries to define variables in js.  Might make more sense in tachyons-js.. but yeah the workaroound is fine for now..

**Comment by jamesmcallister** [comment]
Sorry i forgot to put this in the read me. 

Yes define your css by importing them in.

```html
<!doctype html>
  <html>
    <head>
       <style>
        :root {
         --black: #000;
         --near-black: #111;
         --dark-gray:#333;
        }
        </style>
     </head>
```

**Comment by jamesmcallister** [comment]
Do either of you want to make the readme better?

**Comment by dan-weaver** [comment]
@jamesmcallister sure!
